eight_points_guzzle:
    clients:
        geo_gouv:
            # Write here the host where to do requests
            base_url: "https://geo.api.gouv.fr"

            options:
                timeout: 30

                # Configure headers.
                # More info: http://docs.guzzlephp.org/en/stable/request-options.html#headers
                headers:
                    Accept: "application/json"
                    User-Agent: "EightpointsGuzzleBundle/7.0"

            # Find plugins here:
            # https://github.com/8p/EightPointsGuzzleBundle#known-and-supported-plugins
            plugin: ~

        score_api:

            base_url: "http://scorelo10/"
            options:

                headers:
                    Accept: "application/json"
                    User-Agent: "EightpointsGuzzleBundle/7.0"

        score_apihtml:

                    base_url: "http://scorelo10/"
                    options:

                        headers:
                            Accept: "text/html"
                            User-Agent: "EightpointsGuzzleBundle/7.0"
